create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur double precision, titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur double precision, titre varchar2(255 char), primary key (id));
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
<<<<<<< HEAD
=======
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
>>>>>>> 6110ab075dc6551172a149d9a2f5fe5a50cd313d
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
<<<<<<< HEAD
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
=======
create table livre (id bigint generated by default as identity, auteur varchar(255), titre varchar(255), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
<<<<<<< HEAD
=======
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
>>>>>>> 6110ab075dc6551172a149d9a2f5fe5a50cd313d
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
>>>>>>> 797e86b4b39759afafc44b8d1f93cac7f90c4561
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), titre varchar2(255 char), primary key (id));
