
create sequence hibernate_sequence start with 1 increment by  1;
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table emprunt (id_lecteur number(19,0) not null, id_livre number(19,0) not null, date_debut date, date_fin date, etat varchar2(255 char), incident number(19,0), primary key (id_lecteur, id_livre));
create table incident (id number(19,0) generated as identity, motif varchar2(255 char), primary key (id));
create table livre (id number(19,0) not null, auteur varchar2(255 char), dispo number(1,0), etat varchar2(255 char), titre varchar2(255 char), domaine number(19,0), primary key (id));
create table personne (role varchar2(31 char) not null, id number(19,0) not null, codepostal varchar2(255 char), email varchar2(255 char), nom varchar2(255 char), numallee varchar2(255 char), numtel varchar2(255 char), pays varchar2(255 char), prenom varchar2(255 char), typevoie varchar2(255 char), ville varchar2(255 char), password varchar2(255 char), username varchar2(255 char), primary key (id));
alter table emprunt add constraint FKo6d0w2190bsb61x5yix155mf6 foreign key (incident) references incident;
alter table emprunt add constraint FK4wj65w7ulgjwick3b8hwn5tem foreign key (id_lecteur) references personne;
alter table emprunt add constraint FK2c4tf1n0sr8wpaxsw4f3ec2ur foreign key (id_livre) references livre;
alter table livre add constraint FKno6aivssoq8j0vo4ddxgp9eyd foreign key (domaine) references domaine;
create sequence hibernate_sequence start with 1 increment by  1;
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table emprunt (id_lecteur number(19,0) not null, id_livre number(19,0) not null, date_debut date, date_fin date, etat varchar2(255 char), incident number(19,0), primary key (id_lecteur, id_livre));
create table incident (id number(19,0) generated as identity, motif varchar2(255 char), primary key (id));
create table livre (id number(19,0) not null, auteur varchar2(255 char), dispo number(1,0), etat varchar2(255 char), titre varchar2(255 char), domaine number(19,0), primary key (id));
create table personne (role varchar2(31 char) not null, id number(19,0) not null, codepostal varchar2(255 char), email varchar2(255 char), nom varchar2(255 char), numallee varchar2(255 char), numtel varchar2(255 char), pays varchar2(255 char), prenom varchar2(255 char), typevoie varchar2(255 char), ville varchar2(255 char), password varchar2(255 char), username varchar2(255 char), primary key (id));
alter table emprunt add constraint FKo6d0w2190bsb61x5yix155mf6 foreign key (incident) references incident;
alter table emprunt add constraint FK4wj65w7ulgjwick3b8hwn5tem foreign key (id_lecteur) references personne;
alter table emprunt add constraint FK2c4tf1n0sr8wpaxsw4f3ec2ur foreign key (id_livre) references livre;
alter table livre add constraint FKno6aivssoq8j0vo4ddxgp9eyd foreign key (domaine) references domaine;
