
drop table domaine cascade constraints;
drop table emprunt cascade constraints;
drop table incident cascade constraints;
drop table livre cascade constraints;
drop table personne cascade constraints;
drop sequence hibernate_sequence;
drop table domaine cascade constraints;
drop table emprunt cascade constraints;
drop table incident cascade constraints;
drop table livre cascade constraints;
drop table personne cascade constraints;
drop sequence hibernate_sequence;
drop table if exists domaine CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists incident CASCADE ;
drop table if exists livre CASCADE ;
drop table if exists personne CASCADE ;
drop sequence if exists hibernate_sequence;
drop table if exists domaine CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists incident CASCADE ;
drop table if exists livre CASCADE ;
drop table if exists personne CASCADE ;
drop sequence if exists hibernate_sequence;
drop table domaine cascade constraints;
drop table emprunt cascade constraints;
drop table incident cascade constraints;
drop table livre cascade constraints;
drop table personne cascade constraints;
drop sequence hibernate_sequence;
drop table domaine cascade constraints;
drop table emprunt cascade constraints;
drop table incident cascade constraints;
drop table livre cascade constraints;
drop table personne cascade constraints;
drop sequence hibernate_sequence;
drop table domaine cascade constraints;
drop table emprunt cascade constraints;
drop table incident cascade constraints;
drop table livre cascade constraints;
drop table personne cascade constraints;
drop sequence hibernate_sequence;
drop table domaine cascade constraints;
drop table emprunt cascade constraints;
drop table incident cascade constraints;
drop table livre cascade constraints;
drop table personne cascade constraints;
drop sequence hibernate_sequence;
drop table if exists domaine CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists incident CASCADE ;
drop table if exists livre CASCADE ;
drop table if exists personne CASCADE ;
drop sequence if exists hibernate_sequence;
